name: Build and deploy takelruby 2.6

on:
  schedule: # run daily at midnight CET
    - cron:  '0 2 * * *'
  workflow_dispatch: # allow manual trigger

jobs:
  build-and-deploy-takelbase:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install mutagen
        run: |
          wget -O /tmp/mutagen.tar.gz https://github.com/mutagen-io/mutagen/releases/download/v0.11.8/mutagen_linux_amd64_v0.11.8.tar.gz
          sudo tar xvfz /tmp/mutagen.tar.gz -C /usr/local/bin

      - name: Set up ruby
        uses: ruby/setup-ruby@v1.61.1
        with:
          ruby-version: 2.7

      - name: Install tau
        run: gem install takelage

      - name: Configure tau
        run: |
          echo "docker_entrypoint_options: --no-git --no-gopass --no-gpg --no-ssh" >> $HOME/.takelage.yml
          cat $HOME/.takelage.yml

      - name: Pull takelage image
        run: tau update

      - name: Start an instance of takelage
        run: tau docker container daemon

      - name: Lint ruby
        run: tau docker container command "rake rubylint"

      - name: Lint image with packer
        run: tau docker container command "rake images:ruby26:prod:molecule:lint"

      - name: Build image with packer
        run: tau docker container command "rake images:ruby26:prod:build"

      - name: Test image with packer
        run: tau docker container command "rake images:ruby26:prod:molecule:test"

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push image
        run: |
          tau docker container command "rake dockerhub:ruby26:prod:tag:custom"
          tau docker container command "rake dockerhub:ruby26:prod:push:custom"
